name: CI

on:
  push:
    branches: [main]
  pull_request:

# Cancel any old runs automatically if you push new code before it finishes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libvips

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Installs and caches gems instantly

      - name: Security Check (Vulnerabilities & Gems)
        run: |
          bin/brakeman --no-pager
          bin/bundler-audit --update

      - name: Build Database & Run Tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bin/rails test
